-- AUTO-GENERATED by scripts/sync-task-rewards.mjs — do not hand-edit.
-- Regenerate with `npm run sync-rewards` whenever lesson/challenge/level
-- content changes, then apply this file in the Supabase SQL Editor.
insert into public.task_rewards (task_id, chips, keys, hourglasses) values
  ('htmlcss-lesson-1', 9, 0, 0),
  ('htmlcss-lesson-2', 9, 0, 0),
  ('htmlcss-lesson-3', 10, 0, 0),
  ('htmlcss-lesson-4', 2, 0, 0),
  ('htmlcss-lesson-5', 3, 0, 0),
  ('htmlcss-lesson-6', 3, 0, 0),
  ('htmlcss-lesson-7', 2, 0, 0),
  ('htmlcss-lesson-8', 1, 0, 0),
  ('htmlcss-lesson-9', 2, 0, 0),
  ('htmlcss-lesson-10', 1, 0, 0),
  ('htmlcss-lesson-11', 1, 0, 0),
  ('htmlcss-lesson-12', 2, 0, 0),
  ('htmlcss-lesson-13', 1, 0, 0),
  ('htmlcss-lesson-14', 3, 0, 0),
  ('htmlcss-challenge-1', 2, 0, 0),
  ('htmlcss-challenge-1-nonchip', 0, 0, 0),
  ('htmlcss-challenge-2', 2, 0, 0),
  ('htmlcss-challenge-2-nonchip', 0, 0, 0),
  ('htmlcss-challenge-3', 3, 0, 0),
  ('htmlcss-challenge-3-nonchip', 0, 1, 0),
  ('htmlcss-challenge-4', 4, 0, 0),
  ('htmlcss-challenge-4-nonchip', 0, 1, 0),
  ('htmlcss-challenge-5', 3, 0, 0),
  ('htmlcss-challenge-5-nonchip', 0, 1, 0),
  ('htmlcss-challenge-6', 5, 0, 0),
  ('htmlcss-challenge-6-nonchip', 0, 2, 1),
  ('levelup-2', 0, 1, 0),
  ('levelup-3', 0, 1, 1),
  ('levelup-4', 0, 2, 1),
  ('levelup-5', 0, 2, 2),
  ('levelup-6', 0, 3, 2),
  ('levelup-7', 0, 3, 3),
  ('levelup-8', 0, 7, 5),
  ('levelup-9', 0, 8, 5),
  ('levelup-10', 0, 9, 6),
  ('levelup-11', 0, 10, 6),
  ('levelup-12', 0, 11, 7),
  ('levelup-13', 0, 11, 7),
  ('levelup-14', 0, 12, 8),
  ('levelup-15', 0, 12, 8),
  ('levelup-16', 0, 13, 9)
on conflict (task_id) do update set
  chips       = excluded.chips,
  keys        = excluded.keys,
  hourglasses = excluded.hourglasses;

-- Remove any registry rows for task ids that no longer exist in the data
-- files (e.g. a lesson/challenge/level you deleted). Safe to run — this
-- only affects the registry, not anyone's already-earned rewards.
delete from public.task_rewards
where task_id not in ('htmlcss-lesson-1', 'htmlcss-lesson-2', 'htmlcss-lesson-3', 'htmlcss-lesson-4', 'htmlcss-lesson-5', 'htmlcss-lesson-6', 'htmlcss-lesson-7', 'htmlcss-lesson-8', 'htmlcss-lesson-9', 'htmlcss-lesson-10', 'htmlcss-lesson-11', 'htmlcss-lesson-12', 'htmlcss-lesson-13', 'htmlcss-lesson-14', 'htmlcss-challenge-1', 'htmlcss-challenge-1-nonchip', 'htmlcss-challenge-2', 'htmlcss-challenge-2-nonchip', 'htmlcss-challenge-3', 'htmlcss-challenge-3-nonchip', 'htmlcss-challenge-4', 'htmlcss-challenge-4-nonchip', 'htmlcss-challenge-5', 'htmlcss-challenge-5-nonchip', 'htmlcss-challenge-6', 'htmlcss-challenge-6-nonchip', 'levelup-2', 'levelup-3', 'levelup-4', 'levelup-5', 'levelup-6', 'levelup-7', 'levelup-8', 'levelup-9', 'levelup-10', 'levelup-11', 'levelup-12', 'levelup-13', 'levelup-14', 'levelup-15', 'levelup-16');
