
-- 1. IP tracking for reset attempts (currently username-only rate limiting)
alter table public.reset_attempts add column if not exists ip_address text;
create index if not exists idx_reset_attempts_ip_time on public.reset_attempts (ip_address, attempted_at);

-- 2. New table so register endpoint can be rate limited too (previously unlimited)
create table if not exists public.register_attempts (
  id bigint generated by default as identity primary key,
  ip_address text not null,
  attempted_at timestamptz not null default now()
);
alter table public.register_attempts enable row level security;
-- default-deny: only the service role (edge functions) touches this table directly
create index if not exists idx_register_attempts_ip_time on public.register_attempts (ip_address, attempted_at);

-- 3. Pin search_path on the two flagged functions to prevent search_path hijacking
alter function public.calc_level(integer) set search_path = public;
alter function public.protect_profile_reward_columns() set search_path = public;

-- 4. Revoke anon EXECUTE on SECURITY DEFINER functions that should only ever
--    be called by an authenticated user (they already self-check auth.uid(),
--    this just removes the unnecessary anon grant for defense-in-depth)
revoke execute on function public.claim_race_reward(integer, timestamptz, text) from anon;
revoke execute on function public.claim_weekly_reward(timestamptz) from anon;
revoke execute on function public.increment_profile_reward(integer, integer, integer, text, text) from anon;
revoke execute on function public.merge_guest_progress(integer, integer, integer, text[]) from anon;

-- handle_new_user is trigger-only (fires on auth.users insert as SECURITY DEFINER,
-- doesn't need direct callers) — revoke from both public API roles
revoke execute on function public.handle_new_user() from anon;
revoke execute on function public.handle_new_user() from authenticated;
